# Generated by Django 5.2.7 on 2025-10-09 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferanceAPP', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='descriptionn',
        ),
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(default='Description non fournie', validators=[django.core.validators.MinLengthValidator(30, 'minimum 30 caracteres')]),
            preserve_default=False,
        ),
    ]
